name: Run Python Script

on:
  push:
    branches:
      - main  # 或者您預設的分支名稱
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 選擇您需要的 Python 版本
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run script
      run: |
        python generate_pie_chart.py
        
    - name: Upload generated image
      uses: actions/upload-artifact@v2
      with:
          name: generated-image
          path: code_exp.png

    - name: Commit and push to another repository
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git config --global user.email "weitsunglin@igs.com"
        git config --global user.name "weitsunglin"
        git clone https://github.com/weitsunglin/weitsunglin.git
        cp code_exp.png weitsunglin/code_exp.png
        cd weitsunglin
        git add code_exp.png
        git commit -m "Update code exp image"
        git push https://weitsunglin:${ACCESS_TOKEN}@github.com/weitsunglin/weitsunglin.git main || true

