name: Run Python Script

on:
  push:
    branches:
      - main  # 或者您預設的分支名稱

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 選擇您需要的 Python 版本
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run script
      run: |
        python generate_pie_chart.py
        
    - name: Upload generated image
      uses: actions/upload-artifact@v2
      with:
          name: generated-image
          path: code_exp.png

    - name: Setup Git Configuration
      run: |
        git config --global user.email "weitsunglin@igs.com"
        git config --global user.name "weitsunglin"
      
    - name: Add Remote Repository
      run: git remote add target https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/weitsunglin/weitsunglin.git

    - name: Push Changes
      run: |
        git push target HEAD:main --force

        
